# Generated by Django 5.2.3 on 2025-06-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='farmuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Farm Manager'), ('WORKER', 'Farm Worker')], default='WORKER', max_length=10)),
            ],
            options={
                'verbose_name': 'Farm User',
                'verbose_name_plural': 'Farm Users',
            },
        ),
    ]
