# Generated by Django 5.2.3 on 2025-06-12 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0002_farmuser_date_joined_farmuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('weight', models.FloatField()),
                ('health_status', models.CharField(default='Healthy', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cow',
                'verbose_name_plural': 'Cows',
            },
        ),
    ]
