# Generated by Django 5.2.3 on 2025-06-12 07:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0003_cows'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cows',
            options={'verbose_name_plural': 'cows'},
        ),
        migrations.AddField(
            model_name='cows',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cows',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cows',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cows',
            name='health_status',
            field=models.CharField(choices=[('HEALTHY', 'Healthy'), ('SICK', 'Sick'), ('TREATMENT', 'Under Treatment')], default='HEALTHY', max_length=20),
        ),
    ]
