# Generated by Django 5.2.3 on 2025-06-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0004_alter_cows_options_cows_created_at_cows_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cows',
            name='health_status',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Sick', 'Sick'), ('Treatment', 'Under Treatment')], default='HEALTHY', max_length=20),
        ),
    ]
