# Generated by Django 5.2.3 on 2025-06-12 09:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0006_milkproduction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cows',
            options={'ordering': ['name'], 'verbose_name_plural': 'Cows'},
        ),
        migrations.AlterModelOptions(
            name='milkproduction',
            options={'ordering': ['-date'], 'verbose_name': 'Milk Production Record', 'verbose_name_plural': 'Milk Production Records'},
        ),
        migrations.AlterField(
            model_name='milkproduction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
