# Generated by Django 5.2.3 on 2025-06-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0007_alter_cows_options_alter_milkproduction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cows',
            name='health_status',
            field=models.CharField(choices=[('HEALTHY', 'Healthy'), ('SICK', 'Sick'), ('TREATMENT', 'Under Treatment')], default='HEALTHY', max_length=20),
        ),
    ]
