# Generated by Django 5.2.3 on 2025-06-18 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0009_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cows',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cows', to='farmapp.breed'),
        ),
    ]
