# Generated by Django 5.2.3 on 2025-06-18 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0010_alter_cows_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cows',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmapp.breed'),
        ),
    ]
