# Generated by Django 5.2.3 on 2025-06-18 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0011_alter_cows_breed'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the feed type (e.g., Hay, Silage, Alfalfa)', max_length=100, unique=True)),
                ('dry_matter_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Dry Matter (%)', max_digits=5, null=True)),
                ('crude_protein_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Crude Protein (%)', max_digits=5, null=True)),
                ('metabolizable_energy_mj_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Metabolizable Energy (MJ/kg DM)', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, help_text='Any additional notes or details about this feed type', null=True)),
            ],
            options={
                'verbose_name': 'Feed Type',
                'verbose_name_plural': 'Feed Types',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='cows',
            name='breed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cows', to='farmapp.breed'),
            preserve_default=False,
        ),
    ]
