# Generated by Django 5.2.3 on 2025-06-18 19:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0012_feedtype_alter_cows_breed'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFeedingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(help_text='Name of the worker who logged the feeding', max_length=100)),
                ('total_quantity', models.DecimalField(decimal_places=2, help_text='Total quantity of this feed type distributed', max_digits=10)),
                ('unit', models.CharField(default='kg', help_text="Unit of measurement for the distributed quantity (e.g., 'kg', 'lbs')", max_length=20)),
                ('log_date', models.DateField(default=django.utils.timezone.now, help_text='Date of the feeding log')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about this daily distribution', null=True)),
                ('feed_type', models.ForeignKey(blank=True, help_text='The type of feed distributed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_logs', to='farmapp.feedtype')),
            ],
            options={
                'verbose_name': 'Daily Feeding Log',
                'verbose_name_plural': 'Daily Feeding Logs',
                'ordering': ['-log_date', 'worker_name'],
            },
        ),
    ]
