# Generated by Django 5.2.3 on 2025-06-18 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0013_dailyfeedinglog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyfeedinglog',
            name='feed_type',
        ),
        migrations.RemoveField(
            model_name='dailyfeedinglog',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='dailyfeedinglog',
            name='total_quantity',
        ),
        migrations.RemoveField(
            model_name='dailyfeedinglog',
            name='unit',
        ),
        migrations.AddField(
            model_name='dailyfeedinglog',
            name='general_notes',
            field=models.TextField(blank=True, help_text='General notes about this daily distribution', null=True),
        ),
        migrations.AddField(
            model_name='dailyfeedinglog',
            name='special_feed_vitamins_notes',
            field=models.TextField(blank=True, help_text='Notes about any special feed or vitamins given', null=True),
        ),
        migrations.CreateModel(
            name='DailyFeedQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity of this specific feed type', max_digits=10)),
                ('unit', models.CharField(default='kg', help_text='Unit of measurement for this specific feed quantity', max_length=20)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_quantities', to='farmapp.dailyfeedinglog')),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmapp.feedtype')),
            ],
            options={
                'verbose_name': 'Daily Feed Quantity',
                'verbose_name_plural': 'Daily Feed Quantities',
                'unique_together': {('daily_log', 'feed_type')},
            },
        ),
        migrations.AddField(
            model_name='dailyfeedinglog',
            name='feed_items',
            field=models.ManyToManyField(help_text='Specific feed types and quantities for this log', related_name='daily_feeding_logs', through='farmapp.DailyFeedQuantity', to='farmapp.feedtype'),
        ),
    ]
