# Generated by Django 5.2.3 on 2025-06-19 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0014_remove_dailyfeedinglog_feed_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedingRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bull_name', models.CharField(help_text='Name of the bull used for breeding', max_length=100)),
                ('breeding_date', models.DateField(help_text='Date when the cow was bred')),
                ('insemination_method', models.CharField(choices=[('NATURAL', 'Natural Breeding'), ('AI', 'Artificial Insemination')], default='NATURAL', help_text='Method of breeding', max_length=50)),
                ('expected_calving_date', models.DateField(help_text='Expected date of calving')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about the breeding', null=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_records', to='farmapp.cows')),
            ],
            options={
                'verbose_name': 'Breeding Record',
                'verbose_name_plural': 'Breeding Records',
                'ordering': ['-breeding_date'],
            },
        ),
    ]
