# Generated by Django 5.2.3 on 2025-06-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0015_breedingrecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmuser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
