# Generated by Django 5.2.3 on 2025-06-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0016_alter_farmuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedingrecords',
            name='expected_calving_date',
            field=models.DateField(blank=True, help_text='Expected date of calving', null=True),
        ),
    ]
