# Generated by Django 5.2.3 on 2025-06-19 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0017_alter_breedingrecords_expected_calving_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CowHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(help_text='Date of this health record')),
                ('symptoms', models.TextField(blank=True, help_text='Observed symptoms or health issues', null=True)),
                ('diagnosis', models.TextField(blank=True, help_text='Diagnosis made by a vet or observer', null=True)),
                ('treatment', models.TextField(blank=True, help_text='Treatment administered (e.g., medication, procedure)', null=True)),
                ('medication_administered', models.CharField(blank=True, help_text='Names of medications given', max_length=255, null=True)),
                ('vet_name', models.CharField(blank=True, help_text='Name of the veterinarian (if applicable)', max_length=100, null=True)),
                ('next_checkup_date', models.DateField(blank=True, help_text='Recommended date for next check-up', null=True)),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about the health record', null=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='farmapp.cows')),
            ],
            options={
                'verbose_name': 'Cow Health Record',
                'verbose_name_plural': 'Cow Health Records',
                'ordering': ['-record_date', 'cow__name'],
            },
        ),
    ]
