# Generated by Django 5.2.3 on 2025-06-23 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0018_cowhealthrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedingrecords',
            name='bull_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Calf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ear_tag_number', models.CharField(max_length=50, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('weight_at_birth', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sire', models.CharField(blank=True, max_length=100, null=True)),
                ('is_weaned', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring', to='farmapp.cows')),
            ],
            options={
                'verbose_name_plural': 'Calves',
                'ordering': ['-date_of_birth'],
            },
        ),
    ]
