# Generated by Django 5.2.3 on 2025-06-30 18:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0020_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(default=django.utils.timezone.now)),
                ('quantity_sold', models.FloatField(help_text='Quantity sold in liters')),
                ('price_per_liter', models.DecimalField(decimal_places=2, help_text='Price per liter in local currency', max_digits=10)),
                ('total_sale_amount', models.DecimalField(decimal_places=2, help_text='Total sale amount in local currency', max_digits=10)),
                ('milk_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='farmapp.milkproduction')),
                ('sold_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Milk Sale',
                'verbose_name_plural': 'Milk Sales',
                'ordering': ['-sale_date'],
            },
        ),
    ]
