# Generated by Django 5.2.3 on 2025-07-01 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0021_milksales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('WAGES', 'Wages'), ('FEEDS', 'Feeds'), ('VETERINARY_SERVICES', 'Veterinary Services'), ('FARM_TOOLS', 'Farm Tools'), ('MAINTENANCE', 'Maintenance'), ('TRANSPORT', 'Transport'), ('UTILITIES', 'Utilities'), ('OTHER', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, help_text='User who recorded this expense.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_recorded', to=settings.AUTH_USER_MODEL)),
                ('worker_paid', models.ForeignKey(blank=True, help_text="Worker paid, if category is 'Wages'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
